SELECT CLIENT.NAME, COUNT(PROJECT.ID) AS PROJECT_COUNT
FROM CLIENT
JOIN PROJECT
ON PROJECT.CLIENT_ID = CLIENT.ID
GROUP BY CLIENT.NAME
HAVING COUNT(PROJECT.ID) = (
    SELECT MAX(PROJECTS_COUNT)
    FROM (
        SELECT COUNT(PROJECT.ID) AS PROJECTS_COUNT
        FROM PROJECT
        GROUP BY CLIENT_ID
    )
)
