CREATE TABLE worker (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(1000) NOT NULL CHECK(LENGTH(NAME) > 1),
BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > 1900),
LEVEL VARCHAR(20) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
SALARY INT CHECK(SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(1000) NOT NULL CHECK(LENGTH(NAME) > 1)
);

CREATE TABLE project (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
CLIENT_ID BIGINT REFERENCES CLIENT(ID),
START_DATE DATE,
FINISH_DATE DATE,
CHECK (FINISH_DATE >= START_DATE)
);

CREATE TABLE project_worker (
PROJECT_ID BIGINT REFERENCES PROJECT(ID),
WORKER_ID BIGINT REFERENCES WORKER(ID),
PRIMARY KEY(PROJECT_ID, WORKER_ID)
);
