SELECT PROJECT.NAME, (DATEDIFF('MONTH', START_DATE, FINISH_DATE) * TOTAL_SALARY_PER_MONTH) AS PRICE
FROM PROJECT JOIN (
SELECT PROJECT_WORKER.PROJECT_ID, SUM(WORKER.SALARY) AS TOTAL_SALARY_PER_MONTH
FROM PROJECT_WORKER JOIN WORKER ON PROJECT_WORKER.WORKER_ID = WORKER.ID
GROUP BY PROJECT_ID
) ON PROJECT_ID  = PROJECT.ID
ORDER BY PRICE DESC